# Config file

title: LIVE Competition
email: alvin.tang@mail.utoronto.ca
description: >- # this means to ignore newlines until "baseurl:"
  This is a description.
url: "https://live-fe-test-ss.live-competition.org/" # the base hostname & protocol for your site, e.g. http://example.com
